/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 22 18:33:10 GMT 2020
 */

package bierse.view;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import bierse.view.DefaultInfoViewMouseListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseWheelEvent;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFrame;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DefaultInfoViewMouseListener_ESTest extends DefaultInfoViewMouseListener_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultListCellRenderer.UIResource defaultListCellRenderer_UIResource0 = new DefaultListCellRenderer.UIResource();
      DefaultInfoViewMouseListener defaultInfoViewMouseListener0 = new DefaultInfoViewMouseListener((JFrame) null);
      MouseEvent mouseEvent0 = new MouseEvent(defaultListCellRenderer_UIResource0, 2, (-1L), 0, 870, 870, 870, false, 2);
      defaultInfoViewMouseListener0.mouseClicked(mouseEvent0);
      assertEquals(0, mouseEvent0.getXOnScreen());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultListCellRenderer.UIResource defaultListCellRenderer_UIResource0 = new DefaultListCellRenderer.UIResource();
      DefaultInfoViewMouseListener defaultInfoViewMouseListener0 = new DefaultInfoViewMouseListener((JFrame) null);
      MouseWheelEvent mouseWheelEvent0 = new MouseWheelEvent(defaultListCellRenderer_UIResource0, 0, 0L, (-626), (-1268), 684, 0, 0, 0, false, (-1268), (-626), 0, (-1268));
      // Undeclared exception!
      try { 
        defaultInfoViewMouseListener0.mousePressed(mouseWheelEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("bierse.view.DefaultInfoViewMouseListener", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultListCellRenderer.UIResource defaultListCellRenderer_UIResource0 = new DefaultListCellRenderer.UIResource();
      DefaultInfoViewMouseListener defaultInfoViewMouseListener0 = new DefaultInfoViewMouseListener((JFrame) null);
      MouseEvent mouseEvent0 = new MouseEvent(defaultListCellRenderer_UIResource0, 2, (-1L), 0, 870, 870, 870, false, 2);
      // Undeclared exception!
      try { 
        defaultInfoViewMouseListener0.mouseDragged(mouseEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("bierse.view.DefaultInfoViewMouseListener", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DefaultListCellRenderer.UIResource defaultListCellRenderer_UIResource0 = new DefaultListCellRenderer.UIResource();
      MouseEvent mouseEvent0 = new MouseEvent(defaultListCellRenderer_UIResource0, 2, 2, 2, 2, 2, 2, false, 2);
      DefaultInfoViewMouseListener defaultInfoViewMouseListener0 = new DefaultInfoViewMouseListener((JFrame) null);
      // Undeclared exception!
      try { 
        defaultInfoViewMouseListener0.mouseClicked(mouseEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("bierse.view.DefaultInfoViewMouseListener", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DefaultListCellRenderer.UIResource defaultListCellRenderer_UIResource0 = new DefaultListCellRenderer.UIResource();
      DefaultInfoViewMouseListener defaultInfoViewMouseListener0 = new DefaultInfoViewMouseListener((JFrame) null);
      MouseEvent mouseEvent0 = new MouseEvent(defaultListCellRenderer_UIResource0, 2, 2, 2, 0, 0, 0, false, 2);
      defaultInfoViewMouseListener0.mouseClicked(mouseEvent0);
      assertFalse(mouseEvent0.isMetaDown());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DefaultInfoViewMouseListener defaultInfoViewMouseListener0 = new DefaultInfoViewMouseListener((JFrame) null);
      defaultInfoViewMouseListener0.mouseMoved((MouseEvent) null);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      DefaultInfoViewMouseListener defaultInfoViewMouseListener0 = new DefaultInfoViewMouseListener((JFrame) null);
      defaultInfoViewMouseListener0.mouseEntered((MouseEvent) null);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      DefaultInfoViewMouseListener defaultInfoViewMouseListener0 = new DefaultInfoViewMouseListener((JFrame) null);
      defaultInfoViewMouseListener0.mouseReleased((MouseEvent) null);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      DefaultInfoViewMouseListener defaultInfoViewMouseListener0 = new DefaultInfoViewMouseListener((JFrame) null);
      defaultInfoViewMouseListener0.mouseExited((MouseEvent) null);
  }
}
