/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 22 18:42:53 GMT 2020
 */

package bierse.view;

import org.junit.Test;
import static org.junit.Assert.*;
import bierse.view.KeyMapComboBoxModel;
import bierse.view.MyKeyMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class KeyMapComboBoxModel_ESTest extends KeyMapComboBoxModel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MyKeyMap myKeyMap0 = KeyMapComboBoxModel.getMyKeyMapForKeyCode((-3864));
      assertNull(myKeyMap0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      MyKeyMap myKeyMap0 = KeyMapComboBoxModel.getMyKeyMapForKeyCode(123);
      assertNotNull(myKeyMap0);
      assertEquals("F12", myKeyMap0.getText());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      MyKeyMap myKeyMap0 = KeyMapComboBoxModel.getMyKeyMapForKeyCode(122);
      assertEquals("F11", myKeyMap0.toString());
      assertNotNull(myKeyMap0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      MyKeyMap myKeyMap0 = KeyMapComboBoxModel.getMyKeyMapForKeyCode(121);
      assertNotNull(myKeyMap0);
      assertEquals("F10", myKeyMap0.getText());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      MyKeyMap myKeyMap0 = KeyMapComboBoxModel.getMyKeyMapForKeyCode(120);
      assertNotNull(myKeyMap0);
      assertEquals("F9", myKeyMap0.getText());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      MyKeyMap myKeyMap0 = KeyMapComboBoxModel.getMyKeyMapForKeyCode(118);
      assertNotNull(myKeyMap0);
      assertEquals("F7", myKeyMap0.toString());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      MyKeyMap myKeyMap0 = KeyMapComboBoxModel.getMyKeyMapForKeyCode(117);
      assertEquals("F6", myKeyMap0.getText());
      assertNotNull(myKeyMap0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MyKeyMap myKeyMap0 = KeyMapComboBoxModel.getMyKeyMapForKeyCode(116);
      assertNotNull(myKeyMap0);
      assertEquals("F5", myKeyMap0.toString());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      MyKeyMap myKeyMap0 = KeyMapComboBoxModel.getMyKeyMapForKeyCode(115);
      assertEquals("F4", myKeyMap0.toString());
      assertNotNull(myKeyMap0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      MyKeyMap myKeyMap0 = KeyMapComboBoxModel.getMyKeyMapForKeyCode(114);
      assertEquals(114, myKeyMap0.getCode());
      assertNotNull(myKeyMap0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      MyKeyMap myKeyMap0 = KeyMapComboBoxModel.getMyKeyMapForKeyCode(113);
      assertNotNull(myKeyMap0);
      assertEquals("F2", myKeyMap0.getText());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MyKeyMap myKeyMap0 = KeyMapComboBoxModel.getMyKeyMapForKeyCode(119);
      assertEquals("F8", myKeyMap0.toString());
      assertNotNull(myKeyMap0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MyKeyMap myKeyMap0 = KeyMapComboBoxModel.getMyKeyMapForKeyCode(112);
      assertNotNull(myKeyMap0);
      assertEquals("F1", myKeyMap0.toString());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      KeyMapComboBoxModel keyMapComboBoxModel0 = new KeyMapComboBoxModel();
  }
}
