/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 22 18:48:17 GMT 2020
 */

package bierse.view;

import org.junit.Test;
import static org.junit.Assert.*;
import bierse.view.MyKeyMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MyKeyMap_ESTest extends MyKeyMap_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MyKeyMap myKeyMap0 = new MyKeyMap((String) null, 0);
      myKeyMap0.toString();
      assertEquals(0, myKeyMap0.getCode());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MyKeyMap myKeyMap0 = new MyKeyMap("", 0);
      myKeyMap0.toString();
      assertEquals(0, myKeyMap0.getCode());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MyKeyMap myKeyMap0 = new MyKeyMap((String) null, 0);
      myKeyMap0.getText();
      assertEquals(0, myKeyMap0.getCode());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MyKeyMap myKeyMap0 = new MyKeyMap("WCo<zl,*AQLP", (-160));
      myKeyMap0.getText();
      assertEquals((-160), myKeyMap0.getCode());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MyKeyMap myKeyMap0 = new MyKeyMap("", 0);
      int int0 = myKeyMap0.getCode();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MyKeyMap myKeyMap0 = new MyKeyMap("eB:\"bh=zD", (-3008));
      int int0 = myKeyMap0.getCode();
      assertEquals((-3008), int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MyKeyMap myKeyMap0 = new MyKeyMap("", 0);
      myKeyMap0.getText();
      assertEquals(0, myKeyMap0.getCode());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      MyKeyMap myKeyMap0 = new MyKeyMap("ie9/iepz=yeyJ", 1591);
      int int0 = myKeyMap0.getCode();
      assertEquals(1591, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      MyKeyMap myKeyMap0 = new MyKeyMap("ie9/iepz=yeyJ", 1591);
      myKeyMap0.toString();
      assertEquals(1591, myKeyMap0.getCode());
  }
}
