/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 22 19:21:33 GMT 2020
 */

package org.templateit;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.templateit.MergeRegion;
import org.templateit.Reference;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MergeRegion_ESTest extends MergeRegion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Reference reference0 = new Reference((-450), (-450));
      MergeRegion mergeRegion0 = new MergeRegion(reference0, reference0);
  }
}
