/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 24 19:24:17 GMT 2020
 */

package net.sf.gaeappmanager.google.appengine;

import org.junit.Test;
import static org.junit.Assert.*;
import net.sf.gaeappmanager.google.appengine.Quota;
import net.sf.gaeappmanager.google.appengine.QuotaDetails;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class QuotaDetails_ESTest extends QuotaDetails_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      QuotaDetails quotaDetails0 = new QuotaDetails();
      assertEquals((-1), quotaDetails0.getResetIntervalHours());
      
      quotaDetails0.setResetIntervalHours(0);
      int int0 = quotaDetails0.getResetIntervalHours();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      QuotaDetails quotaDetails0 = new QuotaDetails();
      quotaDetails0.setResetIntervalHours(10);
      int int0 = quotaDetails0.getResetIntervalHours();
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      QuotaDetails quotaDetails0 = new QuotaDetails();
      assertEquals((-1), quotaDetails0.getNextResetWithinHours());
      
      quotaDetails0.setNextResetWithinHours(0);
      int int0 = quotaDetails0.getNextResetWithinHours();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      QuotaDetails quotaDetails0 = new QuotaDetails();
      quotaDetails0.setNextResetWithinHours(2430);
      int int0 = quotaDetails0.getNextResetWithinHours();
      assertEquals(2430, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      QuotaDetails quotaDetails0 = new QuotaDetails();
      Quota quota0 = Quota.IMAGEMANIPULATION_DATA_RECEIVED_FROM_API;
      quotaDetails0.findQuota(quota0);
      assertEquals((-1), quotaDetails0.getResetIntervalHours());
      assertEquals((-1), quotaDetails0.getNextResetWithinHours());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      QuotaDetails quotaDetails0 = new QuotaDetails();
      int int0 = quotaDetails0.getResetIntervalHours();
      assertEquals((-1), int0);
      assertEquals((-1), quotaDetails0.getNextResetWithinHours());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      QuotaDetails quotaDetails0 = new QuotaDetails();
      int int0 = quotaDetails0.getNextResetWithinHours();
      assertEquals((-1), int0);
      assertEquals((-1), quotaDetails0.getResetIntervalHours());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      QuotaDetails quotaDetails0 = new QuotaDetails();
      quotaDetails0.getValues();
      assertEquals((-1), quotaDetails0.getNextResetWithinHours());
      assertEquals((-1), quotaDetails0.getResetIntervalHours());
  }
}
