/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 24 19:31:11 GMT 2020
 */

package net.sf.jniinchi;

import org.junit.Test;
import static org.junit.Assert.*;
import net.sf.jniinchi.INCHI_BOND_TYPE;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class INCHI_BOND_TYPE_ESTest extends INCHI_BOND_TYPE_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      INCHI_BOND_TYPE[] iNCHI_BOND_TYPEArray0 = INCHI_BOND_TYPE.values();
      assertEquals(5, iNCHI_BOND_TYPEArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      INCHI_BOND_TYPE iNCHI_BOND_TYPE0 = INCHI_BOND_TYPE.valueOf("NONE");
      assertEquals(INCHI_BOND_TYPE.NONE, iNCHI_BOND_TYPE0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      INCHI_BOND_TYPE iNCHI_BOND_TYPE0 = INCHI_BOND_TYPE.valueOf("DOUBLE");
      assertEquals(2, iNCHI_BOND_TYPE0.getIndx());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      INCHI_BOND_TYPE.getValue(1178);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      INCHI_BOND_TYPE iNCHI_BOND_TYPE0 = INCHI_BOND_TYPE.getValue(3);
      assertEquals(INCHI_BOND_TYPE.TRIPLE, iNCHI_BOND_TYPE0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      INCHI_BOND_TYPE iNCHI_BOND_TYPE0 = INCHI_BOND_TYPE.getValue(2);
      assertEquals(INCHI_BOND_TYPE.DOUBLE, iNCHI_BOND_TYPE0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      INCHI_BOND_TYPE iNCHI_BOND_TYPE0 = INCHI_BOND_TYPE.getValue(1);
      assertEquals(INCHI_BOND_TYPE.SINGLE, iNCHI_BOND_TYPE0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      INCHI_BOND_TYPE iNCHI_BOND_TYPE0 = INCHI_BOND_TYPE.getValue(4);
      assertEquals(INCHI_BOND_TYPE.ALTERN, iNCHI_BOND_TYPE0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      INCHI_BOND_TYPE iNCHI_BOND_TYPE0 = INCHI_BOND_TYPE.getValue(0);
      int int0 = iNCHI_BOND_TYPE0.getIndx();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      INCHI_BOND_TYPE iNCHI_BOND_TYPE0 = INCHI_BOND_TYPE.ALTERN;
      int int0 = iNCHI_BOND_TYPE0.getIndx();
      assertEquals(4, int0);
  }
}
