/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 26 22:34:35 GMT 2020
 */

package net.springboot.javaguides.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import net.springboot.javaguides.entity.Student;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Student_ESTest extends Student_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Student student0 = new Student((String) null, "");
      student0.setPhoneNo(1L);
      long long0 = student0.getPhoneNo();
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Student student0 = new Student();
      student0.setPhoneNo((-2743L));
      long long0 = student0.getPhoneNo();
      assertEquals((-2743L), long0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Student student0 = new Student();
      String string0 = student0.getName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Student student0 = new Student((String) null, "");
      student0.setName("net.springboot.javaguides.entity.Student");
      String string0 = student0.getName();
      assertEquals("net.springboot.javaguides.entity.Student", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Student student0 = new Student();
      student0.setId(222L);
      long long0 = student0.getId();
      assertEquals(222L, long0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Student student0 = new Student((String) null, "");
      student0.setId((-1L));
      long long0 = student0.getId();
      assertEquals((-1L), long0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Student student0 = new Student();
      String string0 = student0.getEmail();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Student student0 = new Student();
      student0.setEmail("b@)8*i[Yiwx+!Et");
      String string0 = student0.getEmail();
      assertEquals("b@)8*i[Yiwx+!Et", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Student student0 = new Student("", "");
      long long0 = student0.getPhoneNo();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Student student0 = new Student("", "");
      String string0 = student0.getName();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Student student0 = new Student("", "");
      String string0 = student0.getEmail();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Student student0 = new Student("", "");
      long long0 = student0.getId();
      assertEquals(0L, long0);
  }
}
