/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 22 18:41:13 GMT 2020
 */

package bierse.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import bierse.controller.DefaultTableModelController;
import bierse.model.Model;
import bierse.view.IDrinkSellView;
import javax.swing.JLayeredPane;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DefaultTableModelController_ESTest extends DefaultTableModelController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultTableModelController defaultTableModelController0 = new DefaultTableModelController((Model) null, (IDrinkSellView) null);
      Object[][] objectArray0 = new Object[9][1];
      DefaultTableModel defaultTableModel0 = new DefaultTableModel(objectArray0, objectArray0[1]);
      TableModelEvent tableModelEvent0 = new TableModelEvent(defaultTableModel0, 823, 823, 823);
      // Undeclared exception!
      try { 
        defaultTableModelController0.tableChanged(tableModelEvent0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 823 >= 9
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DefaultTableModelController defaultTableModelController0 = new DefaultTableModelController((Model) null, (IDrinkSellView) null);
      Object[] objectArray0 = new Object[3];
      DefaultTableModel defaultTableModel0 = new DefaultTableModel();
      Integer integer0 = JLayeredPane.MODAL_LAYER;
      defaultTableModel0.addColumn((Object) integer0, objectArray0);
      TableModelEvent tableModelEvent0 = new TableModelEvent(defaultTableModel0, 0, (-2937), (-2937), (-2937));
      // Undeclared exception!
      try { 
        defaultTableModelController0.tableChanged(tableModelEvent0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("bierse.controller.DefaultTableModelController", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DefaultTableModelController defaultTableModelController0 = new DefaultTableModelController((Model) null, (IDrinkSellView) null);
      Object[][] objectArray0 = new Object[4][6];
      Object[] objectArray1 = new Object[7];
      objectArray1[0] = (Object) defaultTableModelController0;
      objectArray0[0] = objectArray1;
      DefaultTableModel defaultTableModel0 = new DefaultTableModel(objectArray0, objectArray0[1]);
      TableModelEvent tableModelEvent0 = new TableModelEvent(defaultTableModel0, 0);
      // Undeclared exception!
      try { 
        defaultTableModelController0.tableChanged(tableModelEvent0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // bierse.controller.DefaultTableModelController cannot be cast to java.lang.String
         //
         verifyException("bierse.controller.DefaultTableModelController", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DefaultTableModelController defaultTableModelController0 = new DefaultTableModelController((Model) null, (IDrinkSellView) null);
      DefaultTableModel defaultTableModel0 = new DefaultTableModel();
      TableModelEvent tableModelEvent0 = new TableModelEvent(defaultTableModel0, (-1081), (-1081), (-1081), (-1081));
      defaultTableModelController0.tableChanged(tableModelEvent0);
  }
}
