/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 26 22:27:51 GMT 2020
 */

package org.springframework.samples.petclinic.vet;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.samples.petclinic.vet.Vet;
import org.springframework.samples.petclinic.vet.Vets;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Vets_ESTest extends Vets_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Vets vets0 = new Vets();
      List<Vet> list0 = vets0.getVetList();
      List<Vet> list1 = vets0.getVetList();
      assertSame(list1, list0);
  }
}
