/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 21 14:33:08 GMT 2020
 */

package org.apache.commons.csv;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.commons.csv.Token;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Token_ESTest extends Token_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Token token0 = new Token();
      String string0 = token0.toString();
      assertEquals("INVALID []", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Token token0 = new Token();
      token0.reset();
  }
}
