/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 26 22:49:08 GMT 2020
 */

package com.sivalabs.jblogger.entities;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sivalabs.jblogger.entities.PageView;
import com.sivalabs.jblogger.entities.Post;
import java.time.LocalDateTime;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PageView_ESTest extends PageView_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PageView pageView0 = new PageView();
      boolean boolean0 = pageView0.equals(pageView0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PageView pageView0 = new PageView();
      pageView0.setVisitTime((LocalDateTime) null);
      LocalDateTime localDateTime0 = pageView0.getVisitTime();
      assertNull(localDateTime0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PageView pageView0 = new PageView();
      pageView0.setUrl(".`NWs~:7n8j)X");
      String string0 = pageView0.getUrl();
      assertEquals(".`NWs~:7n8j)X", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PageView pageView0 = new PageView();
      pageView0.setUrl("");
      String string0 = pageView0.getUrl();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PageView pageView0 = new PageView();
      pageView0.setReferrer("PageView(id=null, url=.`NWs~:7n8j)X, referrer=null, visitTime=2014-02-14T20:21:21.320, post=null)");
      String string0 = pageView0.getReferrer();
      assertEquals("PageView(id=null, url=.`NWs~:7n8j)X, referrer=null, visitTime=2014-02-14T20:21:21.320, post=null)", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PageView pageView0 = new PageView();
      pageView0.setReferrer("");
      String string0 = pageView0.getReferrer();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PageView pageView0 = new PageView();
      Post post0 = new Post();
      pageView0.setPost(post0);
      Post post1 = pageView0.getPost();
      assertNull(post1.getId());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PageView pageView0 = new PageView();
      Integer integer0 = new Integer(3441);
      pageView0.setId(integer0);
      Integer integer1 = pageView0.getId();
      assertEquals(3441, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PageView pageView0 = new PageView();
      Integer integer0 = new Integer((-2413));
      pageView0.setId(integer0);
      Integer integer1 = pageView0.getId();
      assertEquals((-2413), (int)integer1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PageView pageView0 = new PageView();
      Post post0 = pageView0.getPost();
      assertNull(post0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PageView pageView0 = new PageView();
      String string0 = pageView0.getUrl();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PageView pageView0 = new PageView();
      Integer integer0 = pageView0.getId();
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PageView pageView0 = new PageView();
      String string0 = pageView0.getReferrer();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PageView pageView0 = new PageView();
      Post post0 = new Post();
      pageView0.setPost(post0);
      pageView0.setReferrer(" Bu8V*q1Izo");
      PageView pageView1 = new PageView();
      pageView1.setReferrer(" Bu8V*q1Izo");
      assertFalse(pageView1.equals((Object)pageView0));
      
      pageView1.setPost(post0);
      boolean boolean0 = pageView1.equals(pageView0);
      assertTrue(pageView1.equals((Object)pageView0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PageView pageView0 = new PageView();
      Post post0 = new Post();
      pageView0.setPost(post0);
      PageView pageView1 = new PageView();
      boolean boolean0 = pageView1.equals(pageView0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PageView pageView0 = new PageView();
      Post post0 = new Post();
      pageView0.setReferrer(" Bu8V*q1Izo");
      PageView pageView1 = new PageView();
      pageView1.setReferrer(" Bu8V*q1Izo");
      assertTrue(pageView1.equals((Object)pageView0));
      
      pageView1.setPost(post0);
      boolean boolean0 = pageView1.equals(pageView0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PageView pageView0 = new PageView();
      PageView pageView1 = new PageView();
      assertTrue(pageView1.equals((Object)pageView0));
      
      pageView1.setVisitTime((LocalDateTime) null);
      boolean boolean0 = pageView0.equals(pageView1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PageView pageView0 = new PageView();
      pageView0.setVisitTime((LocalDateTime) null);
      PageView pageView1 = new PageView();
      assertFalse(pageView1.equals((Object)pageView0));
      
      pageView1.setVisitTime((LocalDateTime) null);
      boolean boolean0 = pageView0.equals(pageView1);
      assertTrue(pageView1.equals((Object)pageView0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PageView pageView0 = new PageView();
      pageView0.setVisitTime((LocalDateTime) null);
      PageView pageView1 = new PageView();
      boolean boolean0 = pageView0.equals(pageView1);
      assertFalse(boolean0);
      assertFalse(pageView1.equals((Object)pageView0));
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PageView pageView0 = new PageView();
      pageView0.setReferrer(" Bu8V*q1Izo");
      pageView0.setUrl("PageView(id=null, url=null, referrer=null, visitTime=2014-02-14T20:21:21.320, post=null)");
      PageView pageView1 = new PageView();
      pageView1.setUrl("PageView(id=null, url=null, referrer=null, visitTime=2014-02-14T20:21:21.320, post=null)");
      boolean boolean0 = pageView1.equals(pageView0);
      assertFalse(boolean0);
      assertFalse(pageView0.equals((Object)pageView1));
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PageView pageView0 = new PageView();
      pageView0.setReferrer(" Bu8V*q1Izo");
      PageView pageView1 = new PageView();
      boolean boolean0 = pageView0.equals(pageView1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PageView pageView0 = new PageView();
      pageView0.setUrl("PageView(id=null, url=null, referrer=null, visitTime=2014-02-14T20:21:21.320, post=null)");
      PageView pageView1 = new PageView();
      boolean boolean0 = pageView1.equals(pageView0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PageView pageView0 = new PageView();
      pageView0.setUrl("PageView(id=null, url=null, referrer=null, visitTime=2014-02-14T20:21:21.320, post=null)");
      PageView pageView1 = new PageView();
      boolean boolean0 = pageView0.equals(pageView1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      PageView pageView0 = new PageView();
      Integer integer0 = new Integer((-2206));
      pageView0.setId(integer0);
      PageView pageView1 = new PageView();
      assertFalse(pageView1.equals((Object)pageView0));
      
      pageView1.setId(integer0);
      boolean boolean0 = pageView0.equals(pageView1);
      assertTrue(pageView1.equals((Object)pageView0));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      PageView pageView0 = new PageView();
      PageView pageView1 = new PageView();
      assertTrue(pageView1.equals((Object)pageView0));
      
      Integer integer0 = new Integer((-4008));
      pageView1.setId(integer0);
      boolean boolean0 = pageView0.equals(pageView1);
      assertFalse(pageView1.equals((Object)pageView0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      PageView pageView0 = new PageView();
      Integer integer0 = new Integer((-2206));
      pageView0.setId(integer0);
      PageView pageView1 = new PageView();
      boolean boolean0 = pageView0.equals(pageView1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      PageView pageView0 = new PageView();
      boolean boolean0 = pageView0.equals("PageView(id=null, url=null, referrer=null, visitTime=2014-02-14T20:21:21.320, post=null)");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      PageView pageView0 = new PageView();
      Post post0 = new Post();
      pageView0.setPost(post0);
      pageView0.hashCode();
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      PageView pageView0 = new PageView();
      pageView0.setVisitTime((LocalDateTime) null);
      pageView0.hashCode();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      PageView pageView0 = new PageView();
      pageView0.setUrl("PageView(id=null, url=null, referrer=null, visitTime=2014-02-14T20:21:21.320, post=null)");
      pageView0.hashCode();
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      PageView pageView0 = new PageView();
      Integer integer0 = new Integer((-2206));
      pageView0.setId(integer0);
      pageView0.hashCode();
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      PageView pageView0 = new PageView();
      pageView0.setReferrer(" Bu8V*q1Izo");
      pageView0.hashCode();
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      PageView pageView0 = new PageView();
      Integer integer0 = new Integer(0);
      pageView0.setId(integer0);
      Integer integer1 = pageView0.getId();
      assertEquals(0, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      PageView pageView0 = new PageView();
      LocalDateTime localDateTime0 = pageView0.getVisitTime();
      pageView0.setVisitTime(localDateTime0);
      assertNull(pageView0.getReferrer());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      PageView pageView0 = new PageView();
      String string0 = pageView0.toString();
      assertEquals("PageView(id=null, url=null, referrer=null, visitTime=2014-02-14T20:21:21.320, post=null)", string0);
  }
}
