/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 26 23:16:04 GMT 2020
 */

package property.maven.plugin;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import property.maven.plugin.Check;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Check_ESTest extends Check_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Check check0 = new Check();
      check0.setCheckValue("property.maven.plugin.Check");
      String string0 = check0.getCheckValue();
      assertEquals("property.maven.plugin.Check", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Check check0 = new Check();
      check0.setCheckName("property.maven.plugin.Check");
      String string0 = check0.getCheckName();
      assertEquals("property.maven.plugin.Check", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Check check0 = new Check();
      String string0 = check0.getCheckName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Check check0 = new Check();
      String string0 = check0.getCheckValue();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Check check0 = new Check();
      check0.setCheckValue("");
      String string0 = check0.getCheckValue();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Check check0 = new Check();
      check0.setCheckName("");
      String string0 = check0.getCheckName();
      assertEquals("", string0);
  }
}
