/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 26 22:56:42 GMT 2020
 */

package com.sivalabs.jblogger;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.sivalabs.jblogger.JBloggerApplication;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JBloggerApplication_ESTest extends JBloggerApplication_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[3];
      // Undeclared exception!
      try { 
        JBloggerApplication.main(stringArray0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/springframework/boot/SpringApplication
         //
         verifyException("com.sivalabs.jblogger.JBloggerApplication", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JBloggerApplication jBloggerApplication0 = new JBloggerApplication();
      // Undeclared exception!
      try { 
        jBloggerApplication0.asyncExecutor();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/springframework/scheduling/concurrent/ThreadPoolTaskExecutor
         //
         verifyException("com.sivalabs.jblogger.JBloggerApplication", e);
      }
  }
}
