/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 26 22:55:26 GMT 2020
 */

package com.sivalabs.jblogger.domain;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sivalabs.jblogger.domain.TimePeriod;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TimePeriod_ESTest extends TimePeriod_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TimePeriod[] timePeriodArray0 = TimePeriod.values();
      assertEquals(5, timePeriodArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TimePeriod timePeriod0 = TimePeriod.valueOf("WEEK");
      assertEquals(TimePeriod.WEEK, timePeriod0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TimePeriod timePeriod0 = TimePeriod.fromString("");
      assertEquals(TimePeriod.TODAY, timePeriod0);
  }
}
